#!/usr/bin/env bash
# install Firewall (ufw)
sudo apt-get install ufw
# Configure ufw to blocks all incoming traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing
# Except port traffic
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
# Restart service
sudo ufw disable
sudo ufw enable
