#!/usr/bin/env bash
# Install nginx web server port 80 and change the header
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow http
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    location /redirect_me {
        return 301 https://www.holbertonschool.com/co;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
    add_header X-Served-By $HOSTNAME;
}" > /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
