#!/usr/bin/env bash
# Install the load balanecer on lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "
frontend front
	bind *:80
	mode http
	default_backend back
backend back
    balance roundrobin
    server 6441-web-01  44.201.238.52:80
    server 6441-web-02  3.95.224.130:80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
